# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    tf_versions: ['1.12']
    onnx_opsets: ['9', '8', '7']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
